### ISSUE TITLE
The app doesn't work with selfoss 2.14 & 2.18, and Fairphone 1 (Android 4.2.2)

### ISSUE THREAD

**Issue by FiSHYsolutions** [aminecmi/ReaderforSelfoss#223]
instead of formatted content, the app shows only parts of it's css source code (see screenshot below).

device: Fairphone 1 (Android 4.2.2)

server: same problem with selfoss 2.14 and 2.18

app: i have no idea which version is installed, because there is no info about that. but it's the current version from f-droid repository (29th sep 2018). the previous version is also affected (same behaviour).

![2018-09-29_03 22 05](https://user-images.githubusercontent.com/222112/46239282-16839400-c397-11e8-9669-75c3af3a2e7d.jpg)

**Comment by aminecmi** [comment]
Hi,

You can see the app version by scrolling at the bottom of the lateral drawer and choosing the "About" item.

Thanks for the report. I'll look into it.

**Comment by FiSHYsolutions** [comment]
nope, can't find something like an "about"-item. no scrolling possible. i can see the items "bugreport" and "preferences" but couldn't find version-informations there. i'm pretty sure we're talking about "Version 1618092681-github (1618092681) - Hinzugefügt am 2018-09-28", cause did an update (from f-droid) on september, 29th. but older (unknown) versions were also affected.

**Comment by aminecmi** [comment]
@FiSHYsolutions the issue is solved. It will be available on f-droid when they build it.

You also can download it from https://jenkins.amine-bou.fr/job/ReaderForSelfoss/lastSuccessfulBuild/artifact/SignApksBuilder-out/selfoss-key/selfoss/app-githubConfig-release-unsigned.apk/app-githubConfig-release.apk when the build is finished, or wait for f-droid to build it (that may take some time)

Also, just FYI, the about button is at the bottom of the drawer after the tags and sources.

<img width="467" alt="capture d ecran 2018-09-30 a 09 40 28" src="https://user-images.githubusercontent.com/510304/46254808-68124880-c495-11e8-8454-fb1a8d98278b.png">

**Comment by FiSHYsolutions** [comment]
f-droid released your update. it works. great job. thank you so much.

**Comment by aminecmi** [comment]
Great !
