### ISSUE TITLE
app marked as {OUTDATED} on Play store

### ISSUE THREAD

**Issue by candardo** [aminecmi/ReaderforSelfoss#284]
The app stopped receiving updates so I checked the Play Store where I read: {OUTDATED} RSS Reader for Selfoss (Beta). What's wrong? Is the app discontinued?

App version is 1719010271-store from 27 jan 19. I'm running Android Pie on a Nokia 6.1 phone. 

![Screenshot_20190404-092844_1](https://user-images.githubusercontent.com/6369278/55537801-48b2dd00-56bd-11e9-9b5a-93f81cd98d45.png)

**Comment by aminecmi** [comment]
@candardo the app is still in development. I just don't have that much time for now.

The outdated tag just means that the app was removed from the app store.

**Comment by candardo** [comment]
> It will be only available on F-Droid from now on.

May I ask why? I'm all for FOSS but you Play has a much broader reach.

**Comment by aminecmi** [comment]
@candardo there is a better reach, of course, and my only purpose is to share the app that was useful for me.

As I am currently having less time to work on the app, I couldn't lose time with the play store deployment process. I lost so much time trying to speed up the process using CI tools. I lost time when the tools didn't work anymore too. 

There's also the 1 star reviews that have no other effect than to make the app less visible. After two or three years on the play store, the other selfoss app that wasn't updated in years still had more reviews, and more visibility that this one. 
Most real "bad reviews" came from people that wouldn't report issues in here, even when asked to, and trying to figure out the problem from a 100 character message wasn't easy.

Having the app on fdroid is so much easier for me, because I only have to push my code to github, and nothing else. I also don't have to worry about the visibility of the app. There's no magic sorting, and there is no fake reviews.

**Comment by candardo** [comment]
I'm sorry to hear that. For what is worth I think that your app was very good - simple enough yet polished and well designed - and easily the best one for Selfoss. Also I didn't know about the extra work required to be on the Play store.
I'll try the last version from F-Droid.
